/* eslint-disable */
import * as types from './graphql';
import type { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "fragment AlertFields on Alert {\n  alertId\n  severity\n  title\n  description\n  status\n  timestamp\n  resolvedAt\n}": typeof types.AlertFieldsFragmentDoc,
    "fragment CustomerFields on Customer {\n  customerId\n  firstName\n  lastName\n  email\n  phone\n  address {\n    street\n    city\n    state\n    zip\n    country\n  }\n  accountStatus\n  createdAt\n}": typeof types.CustomerFieldsFragmentDoc,
    "fragment DeviceFields on NetworkDevice {\n  deviceId\n  type\n  name\n  location {\n    lat\n    lng\n    address\n    region\n  }\n  status\n  metadata {\n    manufacturer\n    model\n    firmwareVersion\n    installDate\n  }\n  configXml\n}": typeof types.DeviceFieldsFragmentDoc,
    "fragment InvoiceFields on Invoice {\n  invoiceNumber\n  billingPeriod {\n    start\n    end\n  }\n  lineItems {\n    description\n    category\n    amount\n  }\n  totalAmount\n  currency\n  status\n  dueDate\n  paidAt\n}": typeof types.InvoiceFieldsFragmentDoc,
    "fragment PlanFields on Plan {\n  planCode\n  name\n  description\n  monthlyPrice\n  currency\n  features {\n    dataLimitGB\n    voiceMinutes\n    smsCount\n    hotspotGB\n    internationalRoaming\n    fiveGAccess\n  }\n  tier\n}": typeof types.PlanFieldsFragmentDoc,
    "fragment TelemetryFields on TelemetryReading {\n  deviceId\n  timestamp\n  cpuPercent\n  memoryPercent\n  bandwidthMbps\n  packetLossPercent\n  temperatureCelsius\n}": typeof types.TelemetryFieldsFragmentDoc,
    "fragment TicketFields on Ticket {\n  ticketId\n  category\n  subject\n  status\n  priority\n  messages {\n    sender\n    senderName\n    content\n    timestamp\n  }\n  createdAt\n  updatedAt\n}": typeof types.TicketFieldsFragmentDoc,
    "mutation PayInvoice($invoiceNumber: String!, $method: PaymentMethod!, $idempotencyKey: String!) {\n  payInvoice(\n    invoiceNumber: $invoiceNumber\n    method: $method\n    idempotencyKey: $idempotencyKey\n  ) {\n    success\n    payment {\n      paymentId\n      amount\n      status\n    }\n    errorMessage\n  }\n}\n\nmutation ToggleAutoPay($customerId: ID!, $enabled: Boolean!) {\n  toggleAutoPay(customerId: $customerId, enabled: $enabled) {\n    customerId\n    autoPayEnabled\n  }\n}": typeof types.PayInvoiceDocument,
    "query GetInvoice($invoiceNumber: String!) {\n  invoice(invoiceNumber: $invoiceNumber) {\n    ...InvoiceFields\n  }\n}\n\nquery GetInvoices($customerId: ID!, $status: InvoiceStatus, $limit: Int) {\n  customer(customerId: $customerId) {\n    customerId\n    invoices(status: $status, limit: $limit) {\n      ...InvoiceFields\n    }\n  }\n}": typeof types.GetInvoiceDocument,
    "mutation ChangePlan($customerId: ID!, $planCode: String!) {\n  changePlan(customerId: $customerId, planCode: $planCode) {\n    success\n    customer {\n      customerId\n      activePlan {\n        planCode\n      }\n    }\n  }\n}\n\nmutation CreateTicket($input: CreateTicketInput!) {\n  createTicket(input: $input) {\n    ticketId\n    status\n  }\n}\n\nmutation AddTicketMessage($ticketId: ID!, $content: String!) {\n  addTicketMessage(ticketId: $ticketId, content: $content) {\n    ticketId\n    messages {\n      content\n      timestamp\n    }\n  }\n}\n\nmutation UpdateProfile($input: UpdateProfileInput!) {\n  updateCustomerProfile(input: $input) {\n    customerId\n    firstName\n    lastName\n  }\n}": typeof types.ChangePlanDocument,
    "query GetCustomer($customerId: ID!) {\n  customer(customerId: $customerId) {\n    ...CustomerFields\n    activePlan {\n      ...PlanFields\n    }\n  }\n}\n\nquery GetPlans($tier: PlanTier) {\n  plans(tier: $tier) {\n    ...PlanFields\n  }\n}\n\nquery GetTickets($customerId: ID!, $status: TicketStatus) {\n  tickets(customerId: $customerId, status: $status) {\n    ...TicketFields\n  }\n}\n\nquery GetTicket($ticketId: ID!) {\n  ticket(ticketId: $ticketId) {\n    ...TicketFields\n    customer {\n      customerId\n      firstName\n      lastName\n    }\n  }\n}": typeof types.GetCustomerDocument,
    "mutation AcknowledgeAlert($alertId: ID!) {\n  acknowledgeAlert(alertId: $alertId) {\n    alertId\n    status\n  }\n}\n\nmutation ResolveAlert($alertId: ID!, $resolution: String!) {\n  resolveAlert(alertId: $alertId, resolution: $resolution) {\n    alertId\n    status\n  }\n}": typeof types.AcknowledgeAlertDocument,
    "query GetDevices($region: String, $status: DeviceStatus) {\n  devices(region: $region, status: $status) {\n    ...DeviceFields\n  }\n}\n\nquery GetDevice($deviceId: ID!) {\n  device(deviceId: $deviceId) {\n    ...DeviceFields\n    connectedDevices {\n      deviceId\n      name\n      status\n    }\n  }\n}\n\nquery GetTelemetry($deviceId: ID!, $timeRange: TimeRange!) {\n  telemetry(deviceId: $deviceId, timeRange: $timeRange) {\n    ...TelemetryFields\n  }\n}\n\nquery GetAlerts($deviceId: ID, $severity: AlertSeverity, $status: AlertStatus) {\n  alerts(deviceId: $deviceId, severity: $severity, status: $status) {\n    ...AlertFields\n    device {\n      deviceId\n      name\n    }\n  }\n}\n\nquery GetAlertsSummary {\n  alertsSummary {\n    critical\n    major\n    minor\n    info\n    total\n  }\n}": typeof types.GetDevicesDocument,
    "subscription OnTicketUpdated($customerId: ID!) {\n  ticketUpdated(customerId: $customerId) {\n    ticketId\n    status\n    messages {\n      content\n      timestamp\n    }\n  }\n}\n\nsubscription OnNewAlert($region: String) {\n  newAlert(region: $region) {\n    alertId\n    severity\n    title\n    timestamp\n  }\n}\n\nsubscription OnTelemetryUpdate($deviceId: ID!) {\n  telemetryUpdate(deviceId: $deviceId) {\n    deviceId\n    timestamp\n    cpuPercent\n    bandwidthMbps\n  }\n}": typeof types.OnTicketUpdatedDocument,
};
const documents: Documents = {
    "fragment AlertFields on Alert {\n  alertId\n  severity\n  title\n  description\n  status\n  timestamp\n  resolvedAt\n}": types.AlertFieldsFragmentDoc,
    "fragment CustomerFields on Customer {\n  customerId\n  firstName\n  lastName\n  email\n  phone\n  address {\n    street\n    city\n    state\n    zip\n    country\n  }\n  accountStatus\n  createdAt\n}": types.CustomerFieldsFragmentDoc,
    "fragment DeviceFields on NetworkDevice {\n  deviceId\n  type\n  name\n  location {\n    lat\n    lng\n    address\n    region\n  }\n  status\n  metadata {\n    manufacturer\n    model\n    firmwareVersion\n    installDate\n  }\n  configXml\n}": types.DeviceFieldsFragmentDoc,
    "fragment InvoiceFields on Invoice {\n  invoiceNumber\n  billingPeriod {\n    start\n    end\n  }\n  lineItems {\n    description\n    category\n    amount\n  }\n  totalAmount\n  currency\n  status\n  dueDate\n  paidAt\n}": types.InvoiceFieldsFragmentDoc,
    "fragment PlanFields on Plan {\n  planCode\n  name\n  description\n  monthlyPrice\n  currency\n  features {\n    dataLimitGB\n    voiceMinutes\n    smsCount\n    hotspotGB\n    internationalRoaming\n    fiveGAccess\n  }\n  tier\n}": types.PlanFieldsFragmentDoc,
    "fragment TelemetryFields on TelemetryReading {\n  deviceId\n  timestamp\n  cpuPercent\n  memoryPercent\n  bandwidthMbps\n  packetLossPercent\n  temperatureCelsius\n}": types.TelemetryFieldsFragmentDoc,
    "fragment TicketFields on Ticket {\n  ticketId\n  category\n  subject\n  status\n  priority\n  messages {\n    sender\n    senderName\n    content\n    timestamp\n  }\n  createdAt\n  updatedAt\n}": types.TicketFieldsFragmentDoc,
    "mutation PayInvoice($invoiceNumber: String!, $method: PaymentMethod!, $idempotencyKey: String!) {\n  payInvoice(\n    invoiceNumber: $invoiceNumber\n    method: $method\n    idempotencyKey: $idempotencyKey\n  ) {\n    success\n    payment {\n      paymentId\n      amount\n      status\n    }\n    errorMessage\n  }\n}\n\nmutation ToggleAutoPay($customerId: ID!, $enabled: Boolean!) {\n  toggleAutoPay(customerId: $customerId, enabled: $enabled) {\n    customerId\n    autoPayEnabled\n  }\n}": types.PayInvoiceDocument,
    "query GetInvoice($invoiceNumber: String!) {\n  invoice(invoiceNumber: $invoiceNumber) {\n    ...InvoiceFields\n  }\n}\n\nquery GetInvoices($customerId: ID!, $status: InvoiceStatus, $limit: Int) {\n  customer(customerId: $customerId) {\n    customerId\n    invoices(status: $status, limit: $limit) {\n      ...InvoiceFields\n    }\n  }\n}": types.GetInvoiceDocument,
    "mutation ChangePlan($customerId: ID!, $planCode: String!) {\n  changePlan(customerId: $customerId, planCode: $planCode) {\n    success\n    customer {\n      customerId\n      activePlan {\n        planCode\n      }\n    }\n  }\n}\n\nmutation CreateTicket($input: CreateTicketInput!) {\n  createTicket(input: $input) {\n    ticketId\n    status\n  }\n}\n\nmutation AddTicketMessage($ticketId: ID!, $content: String!) {\n  addTicketMessage(ticketId: $ticketId, content: $content) {\n    ticketId\n    messages {\n      content\n      timestamp\n    }\n  }\n}\n\nmutation UpdateProfile($input: UpdateProfileInput!) {\n  updateCustomerProfile(input: $input) {\n    customerId\n    firstName\n    lastName\n  }\n}": types.ChangePlanDocument,
    "query GetCustomer($customerId: ID!) {\n  customer(customerId: $customerId) {\n    ...CustomerFields\n    activePlan {\n      ...PlanFields\n    }\n  }\n}\n\nquery GetPlans($tier: PlanTier) {\n  plans(tier: $tier) {\n    ...PlanFields\n  }\n}\n\nquery GetTickets($customerId: ID!, $status: TicketStatus) {\n  tickets(customerId: $customerId, status: $status) {\n    ...TicketFields\n  }\n}\n\nquery GetTicket($ticketId: ID!) {\n  ticket(ticketId: $ticketId) {\n    ...TicketFields\n    customer {\n      customerId\n      firstName\n      lastName\n    }\n  }\n}": types.GetCustomerDocument,
    "mutation AcknowledgeAlert($alertId: ID!) {\n  acknowledgeAlert(alertId: $alertId) {\n    alertId\n    status\n  }\n}\n\nmutation ResolveAlert($alertId: ID!, $resolution: String!) {\n  resolveAlert(alertId: $alertId, resolution: $resolution) {\n    alertId\n    status\n  }\n}": types.AcknowledgeAlertDocument,
    "query GetDevices($region: String, $status: DeviceStatus) {\n  devices(region: $region, status: $status) {\n    ...DeviceFields\n  }\n}\n\nquery GetDevice($deviceId: ID!) {\n  device(deviceId: $deviceId) {\n    ...DeviceFields\n    connectedDevices {\n      deviceId\n      name\n      status\n    }\n  }\n}\n\nquery GetTelemetry($deviceId: ID!, $timeRange: TimeRange!) {\n  telemetry(deviceId: $deviceId, timeRange: $timeRange) {\n    ...TelemetryFields\n  }\n}\n\nquery GetAlerts($deviceId: ID, $severity: AlertSeverity, $status: AlertStatus) {\n  alerts(deviceId: $deviceId, severity: $severity, status: $status) {\n    ...AlertFields\n    device {\n      deviceId\n      name\n    }\n  }\n}\n\nquery GetAlertsSummary {\n  alertsSummary {\n    critical\n    major\n    minor\n    info\n    total\n  }\n}": types.GetDevicesDocument,
    "subscription OnTicketUpdated($customerId: ID!) {\n  ticketUpdated(customerId: $customerId) {\n    ticketId\n    status\n    messages {\n      content\n      timestamp\n    }\n  }\n}\n\nsubscription OnNewAlert($region: String) {\n  newAlert(region: $region) {\n    alertId\n    severity\n    title\n    timestamp\n  }\n}\n\nsubscription OnTelemetryUpdate($deviceId: ID!) {\n  telemetryUpdate(deviceId: $deviceId) {\n    deviceId\n    timestamp\n    cpuPercent\n    bandwidthMbps\n  }\n}": types.OnTicketUpdatedDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "fragment AlertFields on Alert {\n  alertId\n  severity\n  title\n  description\n  status\n  timestamp\n  resolvedAt\n}"): (typeof documents)["fragment AlertFields on Alert {\n  alertId\n  severity\n  title\n  description\n  status\n  timestamp\n  resolvedAt\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "fragment CustomerFields on Customer {\n  customerId\n  firstName\n  lastName\n  email\n  phone\n  address {\n    street\n    city\n    state\n    zip\n    country\n  }\n  accountStatus\n  createdAt\n}"): (typeof documents)["fragment CustomerFields on Customer {\n  customerId\n  firstName\n  lastName\n  email\n  phone\n  address {\n    street\n    city\n    state\n    zip\n    country\n  }\n  accountStatus\n  createdAt\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "fragment DeviceFields on NetworkDevice {\n  deviceId\n  type\n  name\n  location {\n    lat\n    lng\n    address\n    region\n  }\n  status\n  metadata {\n    manufacturer\n    model\n    firmwareVersion\n    installDate\n  }\n  configXml\n}"): (typeof documents)["fragment DeviceFields on NetworkDevice {\n  deviceId\n  type\n  name\n  location {\n    lat\n    lng\n    address\n    region\n  }\n  status\n  metadata {\n    manufacturer\n    model\n    firmwareVersion\n    installDate\n  }\n  configXml\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "fragment InvoiceFields on Invoice {\n  invoiceNumber\n  billingPeriod {\n    start\n    end\n  }\n  lineItems {\n    description\n    category\n    amount\n  }\n  totalAmount\n  currency\n  status\n  dueDate\n  paidAt\n}"): (typeof documents)["fragment InvoiceFields on Invoice {\n  invoiceNumber\n  billingPeriod {\n    start\n    end\n  }\n  lineItems {\n    description\n    category\n    amount\n  }\n  totalAmount\n  currency\n  status\n  dueDate\n  paidAt\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "fragment PlanFields on Plan {\n  planCode\n  name\n  description\n  monthlyPrice\n  currency\n  features {\n    dataLimitGB\n    voiceMinutes\n    smsCount\n    hotspotGB\n    internationalRoaming\n    fiveGAccess\n  }\n  tier\n}"): (typeof documents)["fragment PlanFields on Plan {\n  planCode\n  name\n  description\n  monthlyPrice\n  currency\n  features {\n    dataLimitGB\n    voiceMinutes\n    smsCount\n    hotspotGB\n    internationalRoaming\n    fiveGAccess\n  }\n  tier\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "fragment TelemetryFields on TelemetryReading {\n  deviceId\n  timestamp\n  cpuPercent\n  memoryPercent\n  bandwidthMbps\n  packetLossPercent\n  temperatureCelsius\n}"): (typeof documents)["fragment TelemetryFields on TelemetryReading {\n  deviceId\n  timestamp\n  cpuPercent\n  memoryPercent\n  bandwidthMbps\n  packetLossPercent\n  temperatureCelsius\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "fragment TicketFields on Ticket {\n  ticketId\n  category\n  subject\n  status\n  priority\n  messages {\n    sender\n    senderName\n    content\n    timestamp\n  }\n  createdAt\n  updatedAt\n}"): (typeof documents)["fragment TicketFields on Ticket {\n  ticketId\n  category\n  subject\n  status\n  priority\n  messages {\n    sender\n    senderName\n    content\n    timestamp\n  }\n  createdAt\n  updatedAt\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation PayInvoice($invoiceNumber: String!, $method: PaymentMethod!, $idempotencyKey: String!) {\n  payInvoice(\n    invoiceNumber: $invoiceNumber\n    method: $method\n    idempotencyKey: $idempotencyKey\n  ) {\n    success\n    payment {\n      paymentId\n      amount\n      status\n    }\n    errorMessage\n  }\n}\n\nmutation ToggleAutoPay($customerId: ID!, $enabled: Boolean!) {\n  toggleAutoPay(customerId: $customerId, enabled: $enabled) {\n    customerId\n    autoPayEnabled\n  }\n}"): (typeof documents)["mutation PayInvoice($invoiceNumber: String!, $method: PaymentMethod!, $idempotencyKey: String!) {\n  payInvoice(\n    invoiceNumber: $invoiceNumber\n    method: $method\n    idempotencyKey: $idempotencyKey\n  ) {\n    success\n    payment {\n      paymentId\n      amount\n      status\n    }\n    errorMessage\n  }\n}\n\nmutation ToggleAutoPay($customerId: ID!, $enabled: Boolean!) {\n  toggleAutoPay(customerId: $customerId, enabled: $enabled) {\n    customerId\n    autoPayEnabled\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query GetInvoice($invoiceNumber: String!) {\n  invoice(invoiceNumber: $invoiceNumber) {\n    ...InvoiceFields\n  }\n}\n\nquery GetInvoices($customerId: ID!, $status: InvoiceStatus, $limit: Int) {\n  customer(customerId: $customerId) {\n    customerId\n    invoices(status: $status, limit: $limit) {\n      ...InvoiceFields\n    }\n  }\n}"): (typeof documents)["query GetInvoice($invoiceNumber: String!) {\n  invoice(invoiceNumber: $invoiceNumber) {\n    ...InvoiceFields\n  }\n}\n\nquery GetInvoices($customerId: ID!, $status: InvoiceStatus, $limit: Int) {\n  customer(customerId: $customerId) {\n    customerId\n    invoices(status: $status, limit: $limit) {\n      ...InvoiceFields\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation ChangePlan($customerId: ID!, $planCode: String!) {\n  changePlan(customerId: $customerId, planCode: $planCode) {\n    success\n    customer {\n      customerId\n      activePlan {\n        planCode\n      }\n    }\n  }\n}\n\nmutation CreateTicket($input: CreateTicketInput!) {\n  createTicket(input: $input) {\n    ticketId\n    status\n  }\n}\n\nmutation AddTicketMessage($ticketId: ID!, $content: String!) {\n  addTicketMessage(ticketId: $ticketId, content: $content) {\n    ticketId\n    messages {\n      content\n      timestamp\n    }\n  }\n}\n\nmutation UpdateProfile($input: UpdateProfileInput!) {\n  updateCustomerProfile(input: $input) {\n    customerId\n    firstName\n    lastName\n  }\n}"): (typeof documents)["mutation ChangePlan($customerId: ID!, $planCode: String!) {\n  changePlan(customerId: $customerId, planCode: $planCode) {\n    success\n    customer {\n      customerId\n      activePlan {\n        planCode\n      }\n    }\n  }\n}\n\nmutation CreateTicket($input: CreateTicketInput!) {\n  createTicket(input: $input) {\n    ticketId\n    status\n  }\n}\n\nmutation AddTicketMessage($ticketId: ID!, $content: String!) {\n  addTicketMessage(ticketId: $ticketId, content: $content) {\n    ticketId\n    messages {\n      content\n      timestamp\n    }\n  }\n}\n\nmutation UpdateProfile($input: UpdateProfileInput!) {\n  updateCustomerProfile(input: $input) {\n    customerId\n    firstName\n    lastName\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query GetCustomer($customerId: ID!) {\n  customer(customerId: $customerId) {\n    ...CustomerFields\n    activePlan {\n      ...PlanFields\n    }\n  }\n}\n\nquery GetPlans($tier: PlanTier) {\n  plans(tier: $tier) {\n    ...PlanFields\n  }\n}\n\nquery GetTickets($customerId: ID!, $status: TicketStatus) {\n  tickets(customerId: $customerId, status: $status) {\n    ...TicketFields\n  }\n}\n\nquery GetTicket($ticketId: ID!) {\n  ticket(ticketId: $ticketId) {\n    ...TicketFields\n    customer {\n      customerId\n      firstName\n      lastName\n    }\n  }\n}"): (typeof documents)["query GetCustomer($customerId: ID!) {\n  customer(customerId: $customerId) {\n    ...CustomerFields\n    activePlan {\n      ...PlanFields\n    }\n  }\n}\n\nquery GetPlans($tier: PlanTier) {\n  plans(tier: $tier) {\n    ...PlanFields\n  }\n}\n\nquery GetTickets($customerId: ID!, $status: TicketStatus) {\n  tickets(customerId: $customerId, status: $status) {\n    ...TicketFields\n  }\n}\n\nquery GetTicket($ticketId: ID!) {\n  ticket(ticketId: $ticketId) {\n    ...TicketFields\n    customer {\n      customerId\n      firstName\n      lastName\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation AcknowledgeAlert($alertId: ID!) {\n  acknowledgeAlert(alertId: $alertId) {\n    alertId\n    status\n  }\n}\n\nmutation ResolveAlert($alertId: ID!, $resolution: String!) {\n  resolveAlert(alertId: $alertId, resolution: $resolution) {\n    alertId\n    status\n  }\n}"): (typeof documents)["mutation AcknowledgeAlert($alertId: ID!) {\n  acknowledgeAlert(alertId: $alertId) {\n    alertId\n    status\n  }\n}\n\nmutation ResolveAlert($alertId: ID!, $resolution: String!) {\n  resolveAlert(alertId: $alertId, resolution: $resolution) {\n    alertId\n    status\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query GetDevices($region: String, $status: DeviceStatus) {\n  devices(region: $region, status: $status) {\n    ...DeviceFields\n  }\n}\n\nquery GetDevice($deviceId: ID!) {\n  device(deviceId: $deviceId) {\n    ...DeviceFields\n    connectedDevices {\n      deviceId\n      name\n      status\n    }\n  }\n}\n\nquery GetTelemetry($deviceId: ID!, $timeRange: TimeRange!) {\n  telemetry(deviceId: $deviceId, timeRange: $timeRange) {\n    ...TelemetryFields\n  }\n}\n\nquery GetAlerts($deviceId: ID, $severity: AlertSeverity, $status: AlertStatus) {\n  alerts(deviceId: $deviceId, severity: $severity, status: $status) {\n    ...AlertFields\n    device {\n      deviceId\n      name\n    }\n  }\n}\n\nquery GetAlertsSummary {\n  alertsSummary {\n    critical\n    major\n    minor\n    info\n    total\n  }\n}"): (typeof documents)["query GetDevices($region: String, $status: DeviceStatus) {\n  devices(region: $region, status: $status) {\n    ...DeviceFields\n  }\n}\n\nquery GetDevice($deviceId: ID!) {\n  device(deviceId: $deviceId) {\n    ...DeviceFields\n    connectedDevices {\n      deviceId\n      name\n      status\n    }\n  }\n}\n\nquery GetTelemetry($deviceId: ID!, $timeRange: TimeRange!) {\n  telemetry(deviceId: $deviceId, timeRange: $timeRange) {\n    ...TelemetryFields\n  }\n}\n\nquery GetAlerts($deviceId: ID, $severity: AlertSeverity, $status: AlertStatus) {\n  alerts(deviceId: $deviceId, severity: $severity, status: $status) {\n    ...AlertFields\n    device {\n      deviceId\n      name\n    }\n  }\n}\n\nquery GetAlertsSummary {\n  alertsSummary {\n    critical\n    major\n    minor\n    info\n    total\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "subscription OnTicketUpdated($customerId: ID!) {\n  ticketUpdated(customerId: $customerId) {\n    ticketId\n    status\n    messages {\n      content\n      timestamp\n    }\n  }\n}\n\nsubscription OnNewAlert($region: String) {\n  newAlert(region: $region) {\n    alertId\n    severity\n    title\n    timestamp\n  }\n}\n\nsubscription OnTelemetryUpdate($deviceId: ID!) {\n  telemetryUpdate(deviceId: $deviceId) {\n    deviceId\n    timestamp\n    cpuPercent\n    bandwidthMbps\n  }\n}"): (typeof documents)["subscription OnTicketUpdated($customerId: ID!) {\n  ticketUpdated(customerId: $customerId) {\n    ticketId\n    status\n    messages {\n      content\n      timestamp\n    }\n  }\n}\n\nsubscription OnNewAlert($region: String) {\n  newAlert(region: $region) {\n    alertId\n    severity\n    title\n    timestamp\n  }\n}\n\nsubscription OnTelemetryUpdate($deviceId: ID!) {\n  telemetryUpdate(deviceId: $deviceId) {\n    deviceId\n    timestamp\n    cpuPercent\n    bandwidthMbps\n  }\n}"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;